### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by CalvinDKL** [G047/MultiOgar-Minions#1]
Hey! so how do you split the minions

Cause E and R dont work...

Thanks

**Comment by ItsDavehere** [comment]
I have same Problem

**Comment by CalvinDKL** [comment]
I think its cause the clients dont work

**Comment by G047** [comment]
You need to use an ogar unlimited client

**Comment by CalvinDKL** [comment]
ohh, hmmm. Cant you help me make it work with mine?

**Comment by CalvinDKL** [comment]
maybe just copy paste some code

**Comment by G047** [comment]
yea Its pretty easy

**Comment by CalvinDKL** [comment]
Please help me!

**Comment by CalvinDKL** [comment]
Add me on skype - calvin.leonhardt

**Comment by CalvinDKL** [comment]
You can remove me after!

**Comment by G047** [comment]
All you need to do is use a client that sends the "e" key packet

**Comment by CalvinDKL** [comment]
Can i implement it into my client?

**Comment by G047** [comment]
yes

**Comment by CalvinDKL** [comment]
How???

**Comment by CalvinDKL** [comment]
What code??

**Comment by G047** [comment]
hang on ill get the code for you

**Comment by G047** [comment]
hang on

**Comment by CalvinDKL** [comment]
Thank you man!

**Comment by G047** [comment]
a client like this should work
http://old.ogarul.io

**Comment by G047** [comment]
or you can send the packet 22 when e is pressed

.onkeydown = function(b) {
switch (b.keyCode) {
case 69:
send(22)
break;

**Comment by CalvinDKL** [comment]
how do i do that?=?

just add it like this into my code?

<script>
.onkeydown = function(b) {
switch (b.keyCode) {
case 69:
send(22)
break;
</script>

**Comment by CalvinDKL** [comment]
`.onkeydown = function(b) {
switch (b.keyCode) {
case 69:
send(22)
break;`

**Comment by CalvinDKL** [comment]
? cuz i really want it too work xD

**Comment by CalvinDKL** [comment]
My client doesnt have the Main_Out.js it uses the old agario core.

**Comment by G047** [comment]
try using a different client?

**Comment by CalvinDKL** [comment]
lol xD i spent so much time on this one...

**Comment by CalvinDKL** [comment]
Can you send me a ogar ul client?

**Comment by CalvinDKL** [comment]
Please add me on skype, pls help me!
skype - calvin.leonhardt
you can just remove me afterwards!

**Comment by David1ali12** [comment]
@G047  I have been added minions before 2 months ago and we made Q as switch control but it's same that added to http://alis.io/ Bots mode but you code is clear our code isn't cleanup and it has some bug can you Add Q as Switch control ? thanks.

**Comment by CalvinDKL** [comment]
David, can i talk to you?

**Comment by CalvinDKL** [comment]
One of your devs scammed me, and the owner said he would refund me but never did.
my skype - calvin.leonhardt

**Comment by CalvinDKL** [comment]
Dave there is another multiparty with minions which has the q function
which can also be disabled
